Premium teasers VC-1702
VisualComposer/builder pull request #1019
Opened 2021-01-14 15:20 UTC by nikitahl

2021-01-14 16:24 UTC, pavelthq requested changes

2021-01-14 16:24 UTC, pavelthq commented on public/components/panels/settings/lib/popup/component.js
> +    const url = 'https://visualcomposer.com/premium/?utm_source=vcwb&utm_medium=popup-settings-editor&utm_campaign=gopremium&utm_content=go-premium-button'
please use Utms from `dataManager.get('utm')['...']` and update Utm.php,

the goal is that All Utms is managed from one place.

2021-01-14 16:24 UTC, pavelthq commented on public/components/panels/settings/lib/elementsLock/component.js
> +    const url = 'https://visualcomposer.com/premium/?utm_source=vcwb&utm_medium=element-lock-settings-editor&utm_campaign=gopremium&utm_content=go-premium-button'
please use Utms from `dataManager.get('utm')['...']` and update Utm.php,

the goal is that All Utms is managed from one place.

2021-01-14 20:45 UTC, konutis commented on public/components/panels/editForm/lib/editFormHeader.js
> +    const isAddonAvailable = hubStorage.state('addons').get() && hubStorage.state('addons').get().roleManager
Is there a reason not to use this one - env('VCV_ADDON_ROLE_MANAGER_ENABLED') instead of hubStorage?

2021-01-15 07:57 UTC, nikitahl commented on public/components/panels/editForm/lib/editFormHeader.js
> +    const isAddonAvailable = hubStorage.state('addons').get() && hubStorage.state('addons').get().roleManager
https://github.com/VisualComposer/builder/pull/1019/commits/d15d9e1cee521a0699404d6532a3ee9f09ce38b5

2021-01-19 11:39 UTC, konutis approved these changes

2021-01-19 11:50 UTC, FilipsMasolovs approved these changes

2021-01-19 11:53 UTC, pavelthq approved these changes

2021-01-19 11:55 UTC, merged