Add cloud access agree popup VC-1795
VisualComposer/builder pull request #1045
Opened 2021-01-26 13:06 UTC by konutis

2021-01-26 13:41 UTC, FilipsMasolovs requested changes

2021-01-26 13:41 UTC, FilipsMasolovs commented on public/components/popup/fullPagePopupContainer.js
> +import TermsBox from '../termsBox/component'
import from public

2021-01-26 13:41 UTC, FilipsMasolovs commented on public/components/termsBox/component.js
> +      <div className='vcv-premium-teaser'>
Why use -premium-teser classes in this component?

2021-01-26 13:41 UTC, FilipsMasolovs commented on public/components/termsBox/component.js
> +      isDownloading: false
Are you sure that something is downloading here???

2021-01-26 13:44 UTC, konutis commented on public/components/termsBox/component.js
> +      <div className='vcv-premium-teaser'>
Because these are same classes (with same styling) as in other popup component.

2021-01-26 14:16 UTC, veidenbaums commented on visualcomposer/Helpers/License.php
> +        return $agreeHubTerms ? true : false;
Update this line to 

`return $agreeHubTerms || $this->getType() === 'free' ? true : false;`

2021-01-27 07:58 UTC, FilipsMasolovs approved these changes

2021-01-27 08:29 UTC, pavelthq approved these changes

2021-01-27 08:35 UTC, merged