Add devAddons to the pot file VC-1813
VisualComposer/builder pull request #1182
Opened 2021-03-02 09:14 UTC by alperbuulut

2021-03-02 14:25 UTC, pavelthq requested changes

2021-03-02 14:25 UTC, pavelthq commented on languages/visualcomposer.pot
> +"Language-Team: WPBakery <hello@wpbakery.com>\n"
@veidenbaums it should be visualcomposer.com

2021-03-02 15:28 UTC, veidenbaums commented on languages/visualcomposer.pot
> +"Language-Team: WPBakery <hello@wpbakery.com>\n"
Yes

2021-03-03 06:47 UTC, pavelthq approved these changes

2021-03-03 08:55 UTC, merged