Add public API VC-1929
VisualComposer/builder pull request #1214
Opened 2021-03-15 07:57 UTC by konutis

2021-03-15 18:34 UTC, pavelthq requested changes

2021-03-15 18:34 UTC, pavelthq commented on public/editor.js
> +  Object.defineProperty(window, 'vcv', {
to avoid misunderstanding better to use another variable name, because "window.vcv" already used in view-page.

My suggestion: window.vcwbApi (where vcwb means our editor...) or even "window.vcwbEditorApi" the more describefull name will be the easier it will to explain to 3rd party.

2021-03-16 04:04 UTC, say2me commented on public/editor.js
> +  Object.defineProperty(window, 'vcv', {
I agree let's have a separate global variable.

2021-03-16 13:34 UTC, pavelthq approved these changes

2021-03-16 13:34 UTC, merged