Add groups for Add Templates window VC-1714
VisualComposer/builder pull request #1263
Opened 2021-04-15 11:22 UTC by nikitahl

2021-04-16 07:15 UTC, pavelthq requested changes

2021-04-16 07:15 UTC, pavelthq commented on public/components/panels/addTemplate/addTemplatePanel.js
> +          dataProcessor.appAdminServerRequest({
we don't need extra request for templates usages it can be done in one place:
\VisualComposer\Modules\Editors\Templates\Controller::read

2021-04-16 07:15 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/MostUsedItemsController.php
> +        $this->addFilter('vcv:ajax:templateUsageCount:updateUsage:adminNonce', 'updateTemplateUsage');
remove this and use: \VisualComposer\Modules\Editors\Templates\Controller::read

2021-04-16 07:15 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/MostUsedItemsController.php
> +    protected function updateTemplateUsage(
move this under \VisualComposer\Modules\Editors\Templates\Controller after read() method

2021-04-16 07:16 UTC, pavelthq commented
also update tests for new attributes

2021-04-16 07:33 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/MostUsedItemsController.php
> +    protected function updateTemplateUsage(
we even already have in read()
```
 vcevent(
                        'vcv:saveTemplateUsage',
                        ['response' => [], 'payload' => ['sourceId' => $sourceId, 'templateId' => $id]]
                    );
```

2021-04-16 09:11 UTC, pavelthq commented on visualcomposer/Modules/Editors/Templates/Controller.php
> +                $this->call('updateTemplateUsage', ['templateId' => $id]);
just few lines down there already available 'vcv:saveTemplateUsage' in case if itemdatacollection-enabled. maybe we can get rid of this IF and use already available logic (to avoid duplicated logic for templates usage collection)

2021-04-16 09:12 UTC, pavelthq commented on visualcomposer/Modules/Editors/Templates/Controller.php
> +                $this->call('updateTemplateUsage', ['templateId' => $id]);
@veidenbaums I think we can get rid of this IF (we still don't send any info to our servers in case if itemdatacollection is disabled)

2021-04-16 10:42 UTC, alperbuulut commented on visualcomposer/Modules/Editors/Templates/Controller.php
> +                $this->call('updateTemplateUsage', ['templateId' => $id]);
if we'll remove this if yes we can merge them into one

2021-04-20 15:04 UTC, FilipsMasolovs approved these changes

2021-04-20 15:07 UTC, pavelthq approved these changes

2021-04-21 06:55 UTC, konutis approved these changes

2021-04-21 12:39 UTC, merged