Fixed 2021 theme button style overrides for outlineButton, simpleImageSlider VC-1977
VisualComposer/builder pull request #1336
Opened 2021-05-12 14:03 UTC by orkunaybek

2021-05-12 15:33 UTC, pavelthq requested changes

2021-05-12 15:33 UTC, pavelthq commented on elements/simpleImageSlider/package.json
> +    "vc-webpack-vendors": "2.4.0"
Please don't downgrade (never ever)
Additionally, the build script is correct there, you actually should run yarn install in devElements folder only and then you can use yarn build in every element.

2021-05-12 15:38 UTC, pavelthq commented on elements/simpleImageSlider/package.json
> +    "vc-webpack-vendors": "2.4.0"
Ignore second point the build script should be local "./node_modules", I missed point that it is built-in elements

```
"scripts": {
    "standard": "standard --version && standard",
    "build": "webpack --version && webpack --config=./node_modules/vc-webpack-vendors/webpack.v4.config.js --progress --colors",
    "build-production": "webpack --version && webpack --config=./node_modules/vc-webpack-vendors/webpack.v4.config.production.js -p",
    "watch": "webpack --version && webpack --config=./node_modules/vc-webpack-vendors/webpack.v4.config.js --progress --colors --watch"
  },
```

2021-05-12 18:42 UTC, nikitahl reviewed
The styles work fine on TwentyTwentyOne theme. Need to update the package version to merge.

2021-05-13 09:31 UTC, pavelthq approved these changes

2021-05-13 10:35 UTC, konutis approved these changes

2021-05-13 10:35 UTC, merged