Check color contrast only on Insights panel open VC-2196
VisualComposer/builder pull request #1541
Opened 2021-09-29 20:05 UTC by nikitahl

2021-09-29 20:25 UTC, pavelthq requested changes

2021-09-29 20:25 UTC, pavelthq commented on public/editor/modules/insights/module.js
> +      const triggerCheckContrast = () => {
@nikitahl wrap with debounce will be useful.

2021-09-30 07:20 UTC, pavelthq requested changes

2021-09-30 07:20 UTC, pavelthq commented on public/editor/modules/insights/module.js
> +          debounce(triggerCheckContrast, 250)
I guess it is wrongly wrapped. It should be like 

Const myDebouncedfunc = debounce(function (){}) 
And then run myDebouncedfunc()

2021-09-30 07:20 UTC, pavelthq commented on public/editor/modules/insights/module.js
> +      const triggerCheckContrast = () => {
@nikitahl 
Const myDebouncedfunc = debounce(function (){})
And then run myDebouncedfunc()..

2021-09-30 09:07 UTC, pavelthq approved these changes

2021-09-30 10:16 UTC, konutis approved these changes

2021-09-30 10:16 UTC, merged