Add dashboard teaser license activation link VC-2474
VisualComposer/builder pull request #1778
Opened 2022-01-06 14:38 UTC by nikitahl

2022-01-06 14:42 UTC, pavelthq requested changes

2022-01-06 14:42 UTC, pavelthq commented on visualcomposer/resources/views/partials/teaser.php
> +                <?php esc_html_e('Already have a Premium license?', 'visualcomposer'); ?> <a href="http://localhost:8888/wp-one/wp-admin/admin.php?page=vcv-activate-license&vcv-ref=elements-addelemen
wrong url

2022-01-11 09:09 UTC, pavelthq approved these changes

2022-01-11 09:10 UTC, pavelthq commented
avoid merging until 42 release-beta

2022-01-11 12:32 UTC, orkunaybek approved these changes

2022-01-11 12:32 UTC, merged