<fix> Notifications now are displayed in queue
VisualComposer/builder pull request #1792
Opened 2022-01-12 14:17 UTC by sqarf

2022-01-12 14:39 UTC, pavelthq requested changes
Update commit message (--amend + git push force) to include task id VC-2509 inside commit message, + rename the pull request title to include task ID.

2022-01-12 14:39 UTC, pavelthq commented on public/components/notifications/notificationItem.js
> +  componentDidMount () {}
useless empty method?

2022-01-13 12:31 UTC, pavelthq approved these changes

2022-01-13 13:08 UTC, konutis approved these changes

2022-01-13 13:10 UTC, merged