VC-2632 fix deprecation wp warning with 5.9 wp version
VisualComposer/builder pull request #1853
Opened 2022-01-31 12:05 UTC by OlegApanovich

2022-01-31 12:24 UTC, veidenbaums requested changes

2022-01-31 12:24 UTC, veidenbaums commented on visualcomposer/Modules/Editors/Settings/WordPressSettings/AuthorController.php
> +        if (version_compare($wp_version, '5.8.99', '<')) {
why 5.8.99 instead of 5.9 <

2022-01-31 12:50 UTC, OlegApanovich commented on visualcomposer/Modules/Editors/Settings/WordPressSettings/AuthorController.php
> +        if (version_compare($wp_version, '5.8.99', '<')) {
it not an error, but you are right in such a way  code readability is violated here

2022-01-31 14:05 UTC, veidenbaums requested changes

2022-01-31 19:52 UTC, pavelthq approved these changes

2022-02-01 08:03 UTC, veidenbaums approved these changes

2022-02-01 08:10 UTC, merged