Convert navbar controls to links VC-2298
VisualComposer/builder pull request #1855
Opened 2022-01-31 16:11 UTC by nikitahl

2022-01-31 19:41 UTC, pavelthq requested changes
Plus I recommend to LINT your typescript usage with:
```
yarn lint
```

2022-01-31 19:41 UTC, pavelthq commented on public/components/navbar/controls/assignLayoutControl.tsx
> +    <>
Useless react fragment

2022-01-31 19:41 UTC, pavelthq commented on public/components/navbar/controls/assignLayoutControl.tsx
> +// @ts-ignore
Why ts-ignore? it is not needed

2022-01-31 19:41 UTC, pavelthq commented on public/components/navbar/controls/assignLayoutControl.tsx
> +declare const window: any
no need to do that

2022-01-31 19:41 UTC, pavelthq commented on public/components/navbar/controls/assignLayoutControl.tsx
> +  const adminLink = window && window.vcvWpAdminUrl ? window.vcvWpAdminUrl : ''
change to:

```
const adminLink = window.vcvWpAdminUrl ? window.vcvWpAdminUrl : ''
```

2022-01-31 19:41 UTC, pavelthq commented on public/components/navbar/controls/backendControl.tsx
> +// @ts-ignore
I think ts-ignore can be removed

2022-01-31 19:41 UTC, pavelthq commented on public/components/navbar/controls/backendControl.tsx
> +  let wordpressDashboardButton: ReactNode = null
you can remove `= null` part and instantly assign it as in line 29 (no need for useless null)

2022-01-31 20:27 UTC, nikitahl commented on public/components/navbar/controls/assignLayoutControl.tsx
> +declare const window: any
Typescript shows errors if `window` type is not set

2022-01-31 20:28 UTC, nikitahl commented on public/components/navbar/controls/assignLayoutControl.tsx
> +// @ts-ignore
Same logic in all notifications component files (`public/components/notifications`), so I copied from there.

2022-01-31 20:29 UTC, nikitahl commented on public/components/navbar/controls/assignLayoutControl.tsx
> +    <>
It was there before, wouldn't dare to touch it. Will double-check it is still needed or not.

2022-01-31 20:30 UTC, nikitahl commented on public/components/navbar/controls/assignLayoutControl.tsx
> +  const adminLink = window && window.vcvWpAdminUrl ? window.vcvWpAdminUrl : ''
ok, I think maybe even `const adminLink = window.vcvWpAdminUrl || ''`

2022-01-31 20:31 UTC, nikitahl commented on public/components/navbar/controls/backendControl.tsx
> +// @ts-ignore
Again, the same logic as in all notifications component files (`public/components/notifications`), so I copied from there.

2022-01-31 20:37 UTC, pavelthq commented on public/components/navbar/controls/backendControl.tsx
> +// @ts-ignore
Not needed anymore, will need to update notifications as well.

2022-01-31 20:38 UTC, pavelthq commented on public/components/navbar/controls/assignLayoutControl.tsx
> +// @ts-ignore
Not needed anymore, will need to update notifications as well.

2022-01-31 20:38 UTC, pavelthq commented on public/components/navbar/controls/assignLayoutControl.tsx
> +declare const window: any
Need to check typescript config it should be defined already.
@sqarf @alperbuulut would be good if you will have a look as well.

2022-02-01 09:23 UTC, nikitahl commented on public/components/navbar/controls/assignLayoutControl.tsx
> +declare const window: any
It seems that is the way to go. [Global type declarations are discouraged](https://stackoverflow.com/questions/42233987/how-to-configure-custom-global-interfaces-d-ts-files-for-typescript#answer-42257742). We couldn't find a good example of how it should be handled other than creating a `global.d.ts` file and specifying window type there.

2022-02-01 09:55 UTC, pavelthq commented on public/components/navbar/controls/assignLayoutControl.tsx
> +declare const window: any
ok, need to think about it

2022-02-01 09:55 UTC, pavelthq approved these changes

2022-02-01 09:55 UTC, merged