Vc 2700 popup redux
VisualComposer/builder pull request #1945
Opened 2022-03-30 15:27 UTC by orkunaybek

2022-04-04 07:37 UTC, nikitahl requested changes

2022-04-05 06:43 UTC, nikitahl requested changes

2022-04-05 06:43 UTC, nikitahl commented on public/components/popup/popupContainer.tsx
> +import { Dispatch } from 'redux';
Remove semicolon, also make sure to check all files in PR where it is present.

2022-04-11 11:39 UTC, konutis approved these changes

2022-04-11 11:40 UTC, nikitahl approved these changes

2022-04-11 11:41 UTC, merged