VC-2728 fix wpml error with more than 2 lang autotranslate
VisualComposer/builder pull request #1988
Opened 2022-04-21 11:49 UTC by OlegApanovich

2022-04-21 12:11 UTC, pavelthq requested changes

2022-04-21 12:11 UTC, pavelthq commented on visualcomposer/Modules/Vendors/WpmlController.php
> +    }
as it will be filter return always $response;

2022-04-21 13:26 UTC, pavelthq approved these changes

2022-04-21 14:06 UTC, pavelthq approved these changes

2022-04-21 14:06 UTC, merged

2022-04-28 09:21 UTC, cagdasdag commented on visualcomposer/Modules/Vendors/WpmlController.php
> +        $sql = sprintf("SELECT language_code FROM %sicl_translations WHERE element_id = %s", $wpdb->prefix, $postId);
@pavelthq @OlegApanovich 
As we have is_numeric check it can be unnecessary but maybe using wpdb->prepare could be a better approach here

2022-05-25 09:15 UTC, pavelthq commented on visualcomposer/Modules/Vendors/WpmlController.php
> +        $sql = sprintf("SELECT language_code FROM %sicl_translations WHERE element_id = %s", $wpdb->prefix, $postId);
Thanks, @cagdasdag :)