Vc 2957 wp codestyle
VisualComposer/builder pull request #2167
Opened 2022-08-31 11:41 UTC by pavelthq

2022-09-06 08:11 UTC, OlegApanovich commented on visualcomposer/Framework/helpers.php
> +                // translators: %s: error message
I can see %s in sprint format argument  // translators: %d: error response code  Looks more reasonable

2022-09-06 11:16 UTC, pavelthq commented on visualcomposer/Framework/helpers.php
> +                // translators: %s: error message
fixed

2022-09-06 19:20 UTC, OlegApanovich requested changes

2022-09-07 07:25 UTC, pavelthq commented on visualcomposer/Helpers/AddonViews.php
>          $content = ob_get_clean();
these local variables are not in codestyle. and it is useful when debugging. just remove it from your inspection profile.

2022-09-07 07:43 UTC, pavelthq commented on visualcomposer/Modules/Vendors/WpmlController.php
> +                        '%1$sVisual Composer:%2$s To complete WPML Translation Manager process for the Visual Composer supported pages you will need to run automatic posts update. <a href="%3$s">Upda
fixed

2022-09-07 07:44 UTC, pavelthq commented on visualcomposer/Modules/Vendors/WpmlController.php
> +            // Content Encoded in Base64 as it is safe to use in URL and JSON
we can do that later, like move to helper. but not yet, as it is out of scope. this comment is just informative for wp com codestyle.

2022-09-07 07:44 UTC, pavelthq commented on visualcomposer/resources/views/vendors/dashboard.php
> +                        <?php echo esc_html($title); ?>
fixed

2022-09-07 07:45 UTC, pavelthq commented on visualcomposer/Helpers/Localizations.php
> +                // translators: %s: Plugin url, %s: Plugin version
fixed

2022-09-07 07:45 UTC, pavelthq commented on visualcomposer/Helpers/AssetsShared.php
> +     * @var null
fixed

2022-09-07 07:45 UTC, pavelthq commented on visualcomposer/Helpers/Assets.php
> +     * @return mixed|string
always string will be correct

2022-09-07 07:45 UTC, pavelthq commented on visualcomposer/Helpers/Assets.php
> + *
fixed

2022-09-08 15:01 UTC, veidenbaums approved these changes

2022-09-12 06:32 UTC, OlegApanovich approved these changes

2022-09-12 06:33 UTC, merged