New animations
VisualComposer/builder pull request #2176
Opened 2022-09-06 00:47 UTC by Ryu-k

Added few animations.
- Scaling Entrances.
- Fading Entrances "small" version added.

2022-09-13 10:06 UTC, nikitahl commented on public/sources/attributes/animateDropdown/Component.js
> +    {
As I understand this PR ([2175](https://github.com/VisualComposer/builder/pull/2175/files)) can be dismissed, as these are the same changes in the same file.

2022-09-13 10:12 UTC, nikitahl requested changes

2022-09-13 10:12 UTC, nikitahl commented on public/sources/assetsLibrary/animate/src/animate.css
> +@-webkit-keyframes vce-o-animate--scaleInRight {
scaleInRight has the same rules as scaleInLeft

2022-09-13 10:12 UTC, nikitahl commented on public/sources/assetsLibrary/animate/src/animate.css
> +@keyframes vce-o-animate--scaleInRight {
scaleInRight has the same rules as scaleInLeft

2022-09-13 19:01 UTC, Ryu-k reviewed
changed -50 to 50 in the scaleInRight animation!

2022-09-14 06:03 UTC, nikitahl commented
> changed -50 to 50 in the scaleInRight animation!

Inside animate.bundle.js the `@keyframes vce-o-animate--scaleInRight` still has -50%. Need to re-build the bundle.

2022-09-14 06:04 UTC, nikitahl requested changes

2022-09-14 06:04 UTC, nikitahl commented on public/sources/assetsLibrary/animate/dist/animate.bundle.css
> +[data-vce-animate]{visibility:hidden}[data-vcv-o-animated=true]{-webkit-animation-duration:.7s;animation-duration:.7s;-webkit-animation-fill-mode:both;animation-fill-mode:both;visibility:visible}[dat
Inside animate.bundle.js the @keyframes vce-o-animate--scaleInRight still has -50%. Need to re-build the bundle.

2022-09-16 13:00 UTC, Ryu-k commented
should be ok now, sry for the delay

2022-09-19 08:49 UTC, nikitahl approved these changes

2022-09-19 08:51 UTC, merged