Save anonymous data to postmeta VC-1408
VisualComposer/builder pull request #745
Opened 2020-09-16 14:53 UTC by alperbuulut

2020-09-18 08:22 UTC, pavelthq requested changes

2020-09-18 08:22 UTC, pavelthq commented on public/editor/stores/wordpressData/lib/saveController.js
> +              elementCounts[tag] = { 'page-id': window.vcvSourceID, name: tag, count: 1, type: elementType, action: 'added', license: licenseType, date: dateTime }
Make page id camelCase

2020-09-18 08:22 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +        if ($isAllowed && intval($optionsHelper->getTransient('lastBundleUpdate')) < time()) {
might be never send. need to create lastDataSend or smth like that transient

2020-09-18 08:22 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +                        'source-id' => $postId,
posted must be encrypted to keep anonymous status.

2020-09-18 08:22 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +    protected function getTemplateType($templateData)
This definitely should not be there. Don't copy paste, create helpet or use already available methods or filters

2020-09-18 08:22 UTC, pavelthq commented on visualcomposer/Modules/Editors/Settings/ItemDataCollectionController.php
> +            $url = 'https://visualcomposer.com/cloud-access-terms/';
Wrong url and better to move it to env

2020-09-18 08:22 UTC, pavelthq commented on visualcomposer/Modules/Hub/Elements/ElementDownloadController.php
> +                vcfilter('vcv:saveTeaserDownload', ['source-id' => $sourceId, 'template' => $template]);
why template passed by reference?

2020-09-18 08:22 UTC, pavelthq commented on visualcomposer/Modules/Hub/UpdateController.php
> +    ) {     // Check for update in case if activated
don't see where urlHelper used

2020-09-18 08:22 UTC, pavelthq commented on visualcomposer/Modules/Hub/Elements/ElementDownloadController.php
> +        if ($response && isset($response['templates']) && $isAllowed) {
Why inside initialitePhpElement something about template teaser?

2020-09-18 11:15 UTC, pavelthq commented on visualcomposer/Modules/Editors/Templates/Controller.php
> +                if ($isAllowed) {
put $sourceId declaration inside this if, no need to expose it earlier

2020-09-18 11:16 UTC, pavelthq commented on visualcomposer/Modules/Hub/UpdateController.php
> +use VisualComposer\Helpers\Url;
Url helper not used in this file

2020-09-21 14:51 UTC, alperbuulut commented on visualcomposer/Modules/Editors/Settings/ItemDataCollectionController.php
> +            $url = 'https://visualcomposer.com/cloud-access-terms/';
no longer need it, will remove

2020-09-22 10:33 UTC, alperbuulut commented on visualcomposer/Modules/Hub/Elements/ElementDownloadController.php
> +                vcfilter('vcv:saveTeaserDownload', ['source-id' => $sourceId, 'template' => $template]);
Both element and template downloading using this method and I just needed to separate them with this reference

2020-09-22 11:04 UTC, pavelthq requested changes

2020-09-22 11:04 UTC, pavelthq commented on visualcomposer/Modules/Hub/UpdateController.php
> +    ) {     // Check for update in case if activated
I think this comment placed in wrong line :)

2020-09-22 11:04 UTC, pavelthq commented on visualcomposer/resources/views/settings/fields/yesnotoggle.php
> +    <span><?php echo isset($title) ? $title : ''; ?></span>
maybe esc_html needed there?

2020-09-22 11:04 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +        $this->addFilter('vcv:saveTeaserDownload', 'saveTeaserDownload', 10);
use events not filters if you don't modify the response

2020-09-22 11:04 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +        $this->addFilter('vcv:saveTeaserDownload', 'saveTeaserDownload', 10);
also no need to place weight if it is like default and not override anywhere

2020-09-22 11:04 UTC, pavelthq commented on visualcomposer/Modules/Hub/Elements/ElementDownloadController.php
> +        if ($response && isset($response['templates']) && $isAllowed) {
create another callback for templates. dont use collectElementVariables for template. make code single responsibility.

2020-09-22 11:21 UTC, alperbuulut commented on visualcomposer/Helpers/EditorTemplates.php
> +    {
https://docs.google.com/spreadsheets/d/1e5otbNL74Q1zjuG6Ze6ECa-NRg6cuBG36srAetrbn30/edit#gid=0
There is a column like 'Type' in this sheet and the expected values of the field don't include in the getGroupName method

2020-09-22 15:10 UTC, pavelthq requested changes

2020-09-22 15:10 UTC, pavelthq commented on public/components/popup/popups/dataCollectionPopup.js
> +    window.VCV_DATA_COLLECTION_ENABLED = true
shound't it be from ENV or somewhere else? dynamically from database Or what?

2020-09-22 15:10 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +            $initialUsages += 1;
can be changed to $initialUsages++;

2020-09-22 15:10 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +                wp_remote_get(
I think missing hashed siteUrl to filter by hashedSiteUrl later on

2020-09-22 15:10 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +                // Have at least 10 initial usages
just change to else {}

2020-09-22 15:10 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +            $isEnabled = $optionsHelper->get('settings-itemdatacollection-enabled');
add default value false and change elseif to else

2020-09-22 15:10 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +        $editorEndDate = date('Y-m-d H:i:s', time());
'time()' is default valued already, it can safely be removed.

2020-09-22 15:10 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +            'date' => date('Y-m-d H:i:s', time()),
'time()' is default valued already, it can safely be removed.

2020-09-22 15:10 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +                'date' => date('Y-m-d H:i:s', time()),
'time()' is default valued already, it can safely be removed.

2020-09-22 15:10 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +                'date' => date('Y-m-d H:i:s', time()),
'time()' is default valued already, it can safely be removed.

2020-09-22 15:10 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +                array_push($updatedPostsList, $sourceId);
change to [] as it is 2x faster

2020-09-22 15:10 UTC, pavelthq commented on visualcomposer/Modules/Editors/DataUsage/Controller.php
> +        array_push($editorUsage, array(
'$editorUsage[] = array( 'pageId' => $hashedId, 'license' => ucfirst($licenseType), 'startDate' => $editorStartDate, 'endDate' => $editorEndDate, 'timestamp' => time(), )' here would be up to 2x faster.

2020-09-22 15:11 UTC, pavelthq commented on public/components/popup/popups/dataCollectionPopup.js
> +    window.VCV_DATA_COLLECTION_ENABLED = true
ok, nvm found that it is variable and set to true when button clicked

2020-09-23 09:07 UTC, pavelthq requested changes

2020-09-23 10:10 UTC, pavelthq approved these changes

2020-09-23 10:10 UTC, merged