Update condition for empty dropdown attribute value VC-1551
VisualComposer/builder pull request #817
Opened 2020-10-20 13:59 UTC by nikitahl

2020-10-20 19:29 UTC, konutis approved these changes

2020-10-20 19:42 UTC, pavelthq requested changes

2020-10-20 19:42 UTC, pavelthq commented on public/editor/services/cook/service.js
> +        layoutAtts[fieldKey] = globalOptions[0].value
Fix type error [0] of undefined

2020-10-21 09:00 UTC, pavelthq approved these changes

2020-10-21 09:00 UTC, merged