VC-1558 Updated changelog
VisualComposer/builder pull request #855
Opened 2020-11-09 13:37 UTC by veidenbaums

2020-11-10 11:03 UTC, say2me commented
Will be merge right before release

2020-11-12 10:14 UTC, pavelthq commented on readme.txt
> +- Update:  Blank page wizard has been removed when creating a new page or post for a quicker start
I guess extra space is not needed there

2020-11-12 10:21 UTC, pavelthq requested changes

2020-11-12 10:21 UTC, pavelthq commented on readme.txt
> +- Update:  Theme layout is made as default layout when creating a new page or post
I guess extra space is not needed and there

2020-11-19 16:21 UTC, say2me approved these changes

2020-11-19 16:21 UTC, say2me approved these changes

2020-11-19 16:23 UTC, merged