Featured image field in Settings panel VC-1553
VisualComposer/builder pull request #887
Opened 2020-11-20 07:05 UTC by nikitahl

2020-11-23 12:46 UTC, konutis commented on public/editor/stores/wordpressData/wordpressDataStorage.js
> +    featuredImage.src = current.urls[0].full || current.urls[0].large
Make sure it will not cause fatal error, I would better check if urls and urls[0] is defined. So - current && curent.urls && current.urls[0]. Because there have been fatal errors like this.

2020-11-23 13:16 UTC, nikitahl commented on public/editor/stores/wordpressData/wordpressDataStorage.js
> +    featuredImage.src = current.urls[0].full || current.urls[0].large
Resolved in 0d6ef5c

2020-11-25 07:26 UTC, FilipsMasolovs approved these changes

2020-11-25 11:40 UTC, pavelthq requested changes

2020-11-25 11:40 UTC, pavelthq commented on public/editor/stores/wordpressData/wordpressDataStorage.js
> +        featuredImage = iframe.contentDocument.querySelector('.wp-post-image')
we previously discussed that we will use filter: `post_thumbnail_html` to output custom HTML for correct selector. It will be more safe than using wp-post-image selector

2020-11-25 11:40 UTC, pavelthq commented on visualcomposer/Modules/Editors/Settings/WordPressSettings/FeaturedImageController.php
> +        $this->addFilter(
use vcv:editor:variables

2020-11-25 11:40 UTC, pavelthq commented on visualcomposer/Modules/Editors/Settings/WordPressSettings/FeaturedImageController.php
> +            $response = array_merge(
use editor:variables approach, so response should be changed to $variables[]

2020-11-25 11:40 UTC, pavelthq commented on visualcomposer/Modules/Editors/Settings/WordPressSettings/FeaturedImageController.php
> +        if (!vcvenv('FT_FEATURED_IMAGE_SETTINGS')) {
should be removed or added into env.php

2020-11-25 11:40 UTC, pavelthq commented on public/editor/services/dataManager/service.js
> +      featuredImage: window.VCV_FEATURED_IMAGE
I guess it should be window.VCV_FEATURED_IMAGE() after it will be updated from PHP side to vcv:editor:variables filter

2020-11-25 12:18 UTC, nikitahl commented on public/editor/stores/wordpressData/wordpressDataStorage.js
> +        featuredImage = iframe.contentDocument.querySelector('.wp-post-image')
When there's no image there's nothing to output, also all default featured images have this class `.wp-post-image`.

2020-11-25 12:54 UTC, alperbuulut approved these changes

2020-11-25 12:57 UTC, pavelthq approved these changes

2020-11-25 12:58 UTC, merged