Add new autocomplete and add tags settings VC-1568 VC-1552
VisualComposer/builder pull request #912
Opened 2020-12-03 13:32 UTC by konutis

2020-12-03 14:11 UTC, pavelthq requested changes

2020-12-03 14:11 UTC, pavelthq commented on visualcomposer/Modules/Editors/Settings/WordPressSettings/TagsController.php
> +            'vcv:ajax:autocomplete:findTag:adminNonce',
please change namespace to more specific like
`vcv:ajax:editors:settings:tags:autocomplete:findTag:adminNonce`

2020-12-03 14:11 UTC, pavelthq commented on visualcomposer/Modules/Editors/Settings/WordPressSettings/TagsController.php
> +                $response = array_merge(
Change sturcture to $variables[] it is more efficient

2020-12-03 14:11 UTC, pavelthq commented on visualcomposer/Modules/Editors/Settings/WordPressSettings/TagsController.php
> +    use WpFiltersActions;
you don't use WpFilterActions there, no need to add it

2020-12-03 14:23 UTC, nikitahl commented on public/sources/attributes/autocomplete/Component.js
> +import ReactTagContainer from './libNew/ReactTagContainer'
Maybe rename `libNew` to something more meaningful like `reactTagsLib` or something like that?

2020-12-04 09:29 UTC, pavelthq approved these changes

2020-12-04 09:31 UTC, merged